### ISSUE TITLE
Thanks. Before I STFU...

### ISSUE THREAD

**Issue by mvhenten** [natrim/Cloud9Shortcut#1]
First off, thank you for making a very usefull exention. I've used it a lot lately.
Unfortuntaly, it started crashing on me after some updates.

I noticed the following in my terminal right after the extention crashed:

```
[4427:4427:0924/103606:ERROR:extension_host.cc(367)] Killing renderer for extension pmlkkiikcladbgpdafkklldodkabkcdh for sending an EventAck message with a bad event id.
[4427:4427:0924/103606:ERROR:bad_message.cc(16)] Terminating extension renderer for bad IPC message, reason 3
```

I'm not sure if you're still actively maintaining this or... It might be something the IDE shouldn't do or... 

I'll STFU.

**Comment by natrim** [comment]
it's very probadly already reported chrome bug with setTimeout https://code.google.com/p/chromium/issues/detail?id=473821

**Comment by natrim** [comment]
btw. i didn't manage to reproduce this
could you post some example workspace and description how to exactly get it to crash?
i will reopen this issue if you do.

**Comment by mvhenten** [comment]
Hi @natrim Seems like the issue is with chrome, not your plugin. I'll update chrome (more), try chromium and see what happens. I've had crashes of tabs, but these occur under different circumstances.

I can't share the workspace as it's private. I'll have a look if this happens on one of my public ones; but i hardly spend as much time in there as on @work :)

Thanks,
Matthijs
